name: CI

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential meson valac blueprint-compiler gettext \
            libglib2.0-dev-bin \
            libgtk-4-dev libadwaita-1-dev libjson-glib-dev libgee-0.8-dev \
            libsoup-3.0-dev

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure
        run: meson setup build -Ddevelopment=true

      - name: Build
        run: meson compile -C build
